# Generated by Django 5.2.15 on 2026-06-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='chunk_count',
            field=models.IntegerField(default=0),
        ),
    ]
