# Generated by Django 5.2.15 on 2026-06-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='schools',
            field=models.ManyToManyField(related_name='subjects', to='school_system.school'),
        ),
    ]
